site_name: omnipath-utils
site_url: https://saezlab.github.io/omnipath-utils
repo_url: https://github.com/saezlab/omnipath-utils
repo_name: saezlab/omnipath-utils

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: false
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - ID Translation: guide/mapping.md
    - Taxonomy: guide/taxonomy.md
    - Reference Lists: guide/reflists.md
  - Deployment:
    - Database Build: deployment/database.md
    - Web Service: deployment/server.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_liners: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true
